//! Biome ID definitions and name mapping.

use std::os::raw::c_int;

/// All known biome IDs from cubiomes biomes.h
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
#[repr(i32)]
#[allow(non_camel_case_types)]
pub enum BiomeId {
    Ocean = 0,
    Plains = 1,
    Desert = 2,
    Mountains = 3,
    Forest = 4,
    Taiga = 5,
    Swamp = 6,
    River = 7,
    NetherWastes = 8,
    TheEnd = 9,
    FrozenOcean = 10,
    FrozenRiver = 11,
    SnowyTundra = 12,
    SnowyMountains = 13,
    MushroomFields = 14,
    MushroomFieldShore = 15,
    Beach = 16,
    DesertHills = 17,
    WoodedHills = 18,
    TaigaHills = 19,
    MountainEdge = 20,
    Jungle = 21,
    JungleHills = 22,
    JungleEdge = 23,
    DeepOcean = 24,
    StoneShore = 25,
    SnowyBeach = 26,
    BirchForest = 27,
    BirchForestHills = 28,
    DarkForest = 29,
    SnowyTaiga = 30,
    SnowyTaigaHills = 31,
    GiantTreeTaiga = 32,
    GiantTreeTaigaHills = 33,
    WoodedMountains = 34,
    Savanna = 35,
    SavannaPlateau = 36,
    Badlands = 37,
    WoodedBadlandsPlateau = 38,
    BadlandsPlateau = 39,
    SmallEndIslands = 40,
    EndMidlands = 41,
    EndHighlands = 42,
    EndBarrens = 43,
    WarmOcean = 44,
    LukewarmOcean = 45,
    ColdOcean = 46,
    DeepWarmOcean = 47,
    DeepLukewarmOcean = 48,
    DeepColdOcean = 49,
    DeepFrozenOcean = 50,
    TheVoid = 127,
    // Mutated variants
    SunflowerPlains = 129,
    DesertLakes = 130,
    GravellyMountains = 131,
    FlowerForest = 132,
    TaigaMountains = 133,
    SwampHills = 134,
    IceSpikes = 140,
    ModifiedJungle = 149,
    ModifiedJungleEdge = 151,
    TallBirchForest = 155,
    TallBirchHills = 156,
    DarkForestHills = 157,
    SnowyTaigaMountains = 158,
    GiantSpruceTaiga = 160,
    GiantSpruceTaigaHills = 161,
    ModifiedGravellyMountains = 162,
    ShatteredSavanna = 163,
    ShatteredSavannaPlateau = 164,
    ErodedBadlands = 165,
    ModifiedWoodedBadlandsPlateau = 166,
    ModifiedBadlandsPlateau = 167,
    BambooJungle = 168,
    BambooJungleHills = 169,
    SoulSandValley = 170,
    CrimsonForest = 171,
    WarpedForest = 172,
    BasaltDeltas = 173,
    DripstoneCaves = 174,
    LushCaves = 175,
    Meadow = 177,
    Grove = 178,
    SnowySlopes = 179,
    JaggedPeaks = 180,
    FrozenPeaks = 181,
    StonyPeaks = 182,
    DeepDark = 183,
    MangroveSwamp = 184,
    CherryGrove = 185,
    PaleGarden = 186,
}

impl BiomeId {
    pub fn as_c_int(self) -> c_int {
        self as c_int
    }
}

/// Map a user-friendly biome name string to a BiomeId.
/// Accepts both snake_case (like MC) and common aliases.
pub fn parse_biome_name(name: &str) -> Option<BiomeId> {
    let lower = name.to_lowercase().replace('-', "_").replace(' ', "_");
    match lower.as_str() {
        "ocean" => Some(BiomeId::Ocean),
        "plains" => Some(BiomeId::Plains),
        "desert" => Some(BiomeId::Desert),
        "mountains" | "extreme_hills" | "windswept_hills" => Some(BiomeId::Mountains),
        "forest" => Some(BiomeId::Forest),
        "taiga" => Some(BiomeId::Taiga),
        "swamp" | "swampland" => Some(BiomeId::Swamp),
        "river" => Some(BiomeId::River),
        "nether_wastes" | "hell" => Some(BiomeId::NetherWastes),
        "the_end" | "sky" => Some(BiomeId::TheEnd),
        "frozen_ocean" => Some(BiomeId::FrozenOcean),
        "frozen_river" => Some(BiomeId::FrozenRiver),
        "snowy_tundra" | "snowy_plains" | "ice_plains" => Some(BiomeId::SnowyTundra),
        "snowy_mountains" | "ice_mountains" => Some(BiomeId::SnowyMountains),
        "mushroom_fields" | "mushroom_island" => Some(BiomeId::MushroomFields),
        "mushroom_field_shore" | "mushroom_island_shore" => Some(BiomeId::MushroomFieldShore),
        "beach" => Some(BiomeId::Beach),
        "desert_hills" => Some(BiomeId::DesertHills),
        "wooded_hills" | "forest_hills" => Some(BiomeId::WoodedHills),
        "taiga_hills" => Some(BiomeId::TaigaHills),
        "mountain_edge" | "extreme_hills_edge" => Some(BiomeId::MountainEdge),
        "jungle" => Some(BiomeId::Jungle),
        "jungle_hills" => Some(BiomeId::JungleHills),
        "jungle_edge" | "sparse_jungle" => Some(BiomeId::JungleEdge),
        "deep_ocean" => Some(BiomeId::DeepOcean),
        "stone_shore" | "stony_shore" | "stone_beach" => Some(BiomeId::StoneShore),
        "snowy_beach" | "cold_beach" => Some(BiomeId::SnowyBeach),
        "birch_forest" => Some(BiomeId::BirchForest),
        "birch_forest_hills" => Some(BiomeId::BirchForestHills),
        "dark_forest" | "roofed_forest" => Some(BiomeId::DarkForest),
        "snowy_taiga" | "cold_taiga" => Some(BiomeId::SnowyTaiga),
        "snowy_taiga_hills" | "cold_taiga_hills" => Some(BiomeId::SnowyTaigaHills),
        "giant_tree_taiga" | "mega_taiga" | "old_growth_pine_taiga" => Some(BiomeId::GiantTreeTaiga),
        "giant_tree_taiga_hills" | "mega_taiga_hills" => Some(BiomeId::GiantTreeTaigaHills),
        "wooded_mountains" | "extreme_hills_plus" | "windswept_forest" => Some(BiomeId::WoodedMountains),
        "savanna" => Some(BiomeId::Savanna),
        "savanna_plateau" => Some(BiomeId::SavannaPlateau),
        "badlands" | "mesa" => Some(BiomeId::Badlands),
        "wooded_badlands_plateau" | "wooded_badlands" | "mesa_plateau_f" => Some(BiomeId::WoodedBadlandsPlateau),
        "badlands_plateau" | "mesa_plateau" => Some(BiomeId::BadlandsPlateau),
        "warm_ocean" => Some(BiomeId::WarmOcean),
        "lukewarm_ocean" => Some(BiomeId::LukewarmOcean),
        "cold_ocean" => Some(BiomeId::ColdOcean),
        "deep_warm_ocean" => Some(BiomeId::DeepWarmOcean),
        "deep_lukewarm_ocean" => Some(BiomeId::DeepLukewarmOcean),
        "deep_cold_ocean" => Some(BiomeId::DeepColdOcean),
        "deep_frozen_ocean" => Some(BiomeId::DeepFrozenOcean),
        "sunflower_plains" => Some(BiomeId::SunflowerPlains),
        "desert_lakes" => Some(BiomeId::DesertLakes),
        "gravelly_mountains" | "windswept_gravelly_hills" => Some(BiomeId::GravellyMountains),
        "flower_forest" => Some(BiomeId::FlowerForest),
        "taiga_mountains" => Some(BiomeId::TaigaMountains),
        "swamp_hills" => Some(BiomeId::SwampHills),
        "ice_spikes" => Some(BiomeId::IceSpikes),
        "modified_jungle" => Some(BiomeId::ModifiedJungle),
        "modified_jungle_edge" => Some(BiomeId::ModifiedJungleEdge),
        "tall_birch_forest" | "old_growth_birch_forest" => Some(BiomeId::TallBirchForest),
        "tall_birch_hills" => Some(BiomeId::TallBirchHills),
        "dark_forest_hills" => Some(BiomeId::DarkForestHills),
        "snowy_taiga_mountains" => Some(BiomeId::SnowyTaigaMountains),
        "giant_spruce_taiga" | "old_growth_spruce_taiga" => Some(BiomeId::GiantSpruceTaiga),
        "giant_spruce_taiga_hills" => Some(BiomeId::GiantSpruceTaigaHills),
        "modified_gravelly_mountains" => Some(BiomeId::ModifiedGravellyMountains),
        "shattered_savanna" | "windswept_savanna" => Some(BiomeId::ShatteredSavanna),
        "shattered_savanna_plateau" => Some(BiomeId::ShatteredSavannaPlateau),
        "eroded_badlands" => Some(BiomeId::ErodedBadlands),
        "modified_wooded_badlands_plateau" => Some(BiomeId::ModifiedWoodedBadlandsPlateau),
        "modified_badlands_plateau" => Some(BiomeId::ModifiedBadlandsPlateau),
        "bamboo_jungle" => Some(BiomeId::BambooJungle),
        "bamboo_jungle_hills" => Some(BiomeId::BambooJungleHills),
        "soul_sand_valley" => Some(BiomeId::SoulSandValley),
        "crimson_forest" => Some(BiomeId::CrimsonForest),
        "warped_forest" => Some(BiomeId::WarpedForest),
        "basalt_deltas" => Some(BiomeId::BasaltDeltas),
        "dripstone_caves" => Some(BiomeId::DripstoneCaves),
        "lush_caves" => Some(BiomeId::LushCaves),
        "meadow" => Some(BiomeId::Meadow),
        "grove" => Some(BiomeId::Grove),
        "snowy_slopes" => Some(BiomeId::SnowySlopes),
        "jagged_peaks" => Some(BiomeId::JaggedPeaks),
        "frozen_peaks" => Some(BiomeId::FrozenPeaks),
        "stony_peaks" => Some(BiomeId::StonyPeaks),
        "deep_dark" => Some(BiomeId::DeepDark),
        "mangrove_swamp" => Some(BiomeId::MangroveSwamp),
        "cherry_grove" => Some(BiomeId::CherryGrove),
        "pale_garden" => Some(BiomeId::PaleGarden),
        _ => None,
    }
}

/// Get a display name for a biome ID integer.
pub fn biome_name(id: c_int) -> &'static str {
    match id {
        0 => "ocean",
        1 => "plains",
        2 => "desert",
        3 => "mountains",
        4 => "forest",
        5 => "taiga",
        6 => "swamp",
        7 => "river",
        8 => "nether_wastes",
        9 => "the_end",
        10 => "frozen_ocean",
        11 => "frozen_river",
        12 => "snowy_tundra",
        13 => "snowy_mountains",
        14 => "mushroom_fields",
        15 => "mushroom_field_shore",
        16 => "beach",
        17 => "desert_hills",
        18 => "wooded_hills",
        19 => "taiga_hills",
        20 => "mountain_edge",
        21 => "jungle",
        22 => "jungle_hills",
        23 => "jungle_edge",
        24 => "deep_ocean",
        25 => "stone_shore",
        26 => "snowy_beach",
        27 => "birch_forest",
        28 => "birch_forest_hills",
        29 => "dark_forest",
        30 => "snowy_taiga",
        31 => "snowy_taiga_hills",
        32 => "giant_tree_taiga",
        33 => "giant_tree_taiga_hills",
        34 => "wooded_mountains",
        35 => "savanna",
        36 => "savanna_plateau",
        37 => "badlands",
        38 => "wooded_badlands_plateau",
        39 => "badlands_plateau",
        44 => "warm_ocean",
        45 => "lukewarm_ocean",
        46 => "cold_ocean",
        47 => "deep_warm_ocean",
        48 => "deep_lukewarm_ocean",
        49 => "deep_cold_ocean",
        50 => "deep_frozen_ocean",
        127 => "the_void",
        129 => "sunflower_plains",
        130 => "desert_lakes",
        131 => "gravelly_mountains",
        132 => "flower_forest",
        133 => "taiga_mountains",
        134 => "swamp_hills",
        140 => "ice_spikes",
        149 => "modified_jungle",
        151 => "modified_jungle_edge",
        155 => "tall_birch_forest",
        156 => "tall_birch_hills",
        157 => "dark_forest_hills",
        158 => "snowy_taiga_mountains",
        160 => "giant_spruce_taiga",
        161 => "giant_spruce_taiga_hills",
        162 => "modified_gravelly_mountains",
        163 => "shattered_savanna",
        164 => "shattered_savanna_plateau",
        165 => "eroded_badlands",
        166 => "modified_wooded_badlands_plateau",
        167 => "modified_badlands_plateau",
        168 => "bamboo_jungle",
        169 => "bamboo_jungle_hills",
        170 => "soul_sand_valley",
        171 => "crimson_forest",
        172 => "warped_forest",
        173 => "basalt_deltas",
        174 => "dripstone_caves",
        175 => "lush_caves",
        177 => "meadow",
        178 => "grove",
        179 => "snowy_slopes",
        180 => "jagged_peaks",
        181 => "frozen_peaks",
        182 => "stony_peaks",
        183 => "deep_dark",
        184 => "mangrove_swamp",
        185 => "cherry_grove",
        186 => "pale_garden",
        _ => "unknown",
    }
}